language: ruby
cache: bundler
rvm:
- ruby-1.9.2
- ruby-1.9.3
- ruby-2.1.4
# - rbx-2.2.10
env:
  matrix:
    secure: YBwgllw5lzpeqcvjKIAPuFjR1F0BIo+tYlj6WQ73zUyKHHAbCtV2RKXdWRgB+U+SDGvb1FhEZKGu4EcGURo8zcHGua8uB1EqoHHl+Qb3qcVHhrVw7xd6XwAJHq2kgj1BTNxA6Gbwu5UJr1v7A/eSwlvH+FDErnM73vhaRdzaQL0=
script: bundle exec rake travis
after_success:
- coveralls
